class CityData {
  const CityData._();

  static const List<String> states = [
    'Khartoum',
    'Al Jazirah',
    'Northern',
    'River Nile',
    'Red Sea',
    'Kassala',
    'Gedaref',
    'Sennar',
    'White Nile',
    'Blue Nile',
    'North Kordofan',
    'South Kordofan',
    'West Kordofan',
    'North Darfur',
    'South Darfur',
    'West Darfur',
    'Central Darfur',
    'East Darfur',
  ];

  static const Map<String, List<String>> citiesByState = {
    'Khartoum': [
      'Khartoum',
      'Omdurman',
      'Bahri',
      'Ombada',
      'Karary',
      'Sharg En Nile',
      'Jabal Awliya',
    ],
    'Al Jazirah': [
      'Wad Madani',
      'Al Hasaheisa',
      'Al Kamlin',
      'Al Managil',
      'East Al Gazera',
      'South Al Gazera',
      'Om Al Qura',
      'Al-Qurashi 24',
    ],
    'Northern': [
      'Dongola',
      'Merowe',
      'Halfa',
      'Al Goled',
      'Al Burgaig',
      'Al Dabbah',
      'Delgo',
    ],
    'River Nile': [
      'Atbara',
      'Shendi',
      'Ad-Damir',
      'Berber',
      'Al Matammah',
      'Al Buhaira',
      'Abu Hamad',
    ],
    'Red Sea': [
      'Port Sudan',
      'Sinkat',
      'Tokar',
      'Halaib',
      'Suakin',
      'Jubayt',
      'Hayaa',
    ],
    'Kassala': [
      'Kassala',
      'Khashm El Girba',
      'Al Quresha',
      'Ar Rahad',
      'Al Gash',
      'Al Humr',
      'Telkuk',
    ],
    'Gedaref': [
      'Al Qadarif',
      'Doka',
      'Al Faw',
      'Al Butanah',
      'Al Rahad',
      'Galabat',
      'Basunda',
      'Qala an Nahal',
      'Wasat Al Gedaref',
    ],
    'Sennar': [
      'Sennar',
      'Sinja',
      'Ad Dinder',
      'Abu Hujar',
      'As Suki',
      'East Sennar',
      'Dali',
      'Mazan',
      'Al Salam',
    ],
    'White Nile': [
      'Kosti',
      'Rabak',
      'Ed Dueim',
      'Tendalti',
      'Al Gitaina',
      'Al Jabalain',
      'As Salam',
      'Um Rimta',
      'Quli',
    ],
    'Blue Nile': [
      'Ad-Damazin',
      'Ar Roseires',
      'Baw',
      'Geisan',
      'Kurmuk',
      'At Tadamon',
      'Wad Al Mahi',
      'Bau',
    ],
    'North Kordofan': [
      'El Obeid',
      'Bara',
      'Umm Rawaba',
      'Ar Rahad',
      'Sodari',
      'Gebrat Al Sheikh',
      'Shaikan',
      'West Bara',
      'Abu Zabad',
    ],
    'South Kordofan': [
      'Kadugli',
      'Dilling',
      'Talodi',
      'Abu Jubeiha',
      'Heiban',
      'Rashad',
      'Al Leri',
      'Delami',
      'Buram',
      'Habila',
    ],
    'West Kordofan': [
      'An Nuhud',
      'Al Fula',
      'Babanusa',
      'Al Khiwai',
      'As Salam',
      'Abu Zabad',
      'Lagawa',
      'Wad Bandah',
      'Muglad',
    ],
    'North Darfur': [
      'Al Fasher',
      'Kutum',
      'Mellit',
      'Kabkabiya',
      'Tawila',
      'Dar As Salam',
      'Saraf Omra',
      'Korma',
      'Umm Kadadah',
    ],
    'South Darfur': [
      'Nyala',
      'Kass',
      'Tulus',
      'Ed al Fursan',
      'Kubum',
      'Rehed Al Birdi',
      'Buram',
      'As Salam',
      'Bielel',
      'Nyala Janoub',
    ],
    'West Darfur': [
      'El Geneina',
      'Habila',
      'Foro Baranga',
      'Kulbus',
      'Jebel Moon',
      'Kereinik',
      'Sirba',
      'Beida',
      'Ardamata',
    ],
    'Central Darfur': [
      'Zalingei',
      'Azum',
      'Wadi Salih',
      'Mukjar',
      'Umm Dukhun',
      'Nertiti',
      'Garsila',
      'Bendasi',
      'Rokoro',
    ],
    'East Darfur': [
      'Ed Daein',
      'Adila',
      'Abu Karinka',
      'Bahr al Arab',
      'Yassin',
      'Asalaya',
      'Shaeria',
      'Lagein',
    ],
  };

  static final List<String> allCities =
      citiesByState.values.expand((cities) => cities).toList(growable: false);
}
